openapi: "3.0.0"
info:
  version: 1.0.0
  title: Data Export
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /:
    post:
      summary: Create a signed url
      operationId: generate_signed_url
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Distribution'
      responses:
        '200':
          description: Url valid for 5 minutes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignedUrl'
components:
  schemas:
    Distribution:
      required:
        - bucket
        - key
      properties:
        bucket:
          type: string
        key:
          type: string
    SignedUrl:
      required:
        - url
      properties:
        url:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string