frameworkVersion: ">=3.38.0 <4.0.0"

service: data-exporter

provider:
  name: aws
  runtime: python3.11
  region: ${opt:region, 'eu-west-1'}
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  logRetentionInDays: 90
  iam:
    role:
      permissionsBoundary: "arn:aws:iam::${aws:accountId}:policy/oslokommune/oslokommune-boundary"
      managedPolicies:
        - 'arn:aws:iam::${aws:accountId}:policy/data-exporter-policy'
        - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    BUCKET: "ok-origo-dataplatform-${self:provider.stage}"
    METADATA_API_URL: ${ssm:/dataplatform/shared/api-gateway-url}/metadata
    ENABLE_AUTH: true
    KEYCLOAK_SERVER: ${ssm:/dataplatform/shared/keycloak-server-url}
    KEYCLOAK_REALM: api-catalog
    RESOURCE_SERVER_CLIENT_ID: okdata-resource-server
    CLIENT_ID: data-uploader
    CLIENT_SECRET: ${ssm:/dataplatform/data-uploader/keycloak-client-secret}
    SERVICE_NAME: ${self:service}

plugins:
  - serverless-better-credentials # must be first
  - "@kakkuk/serverless-aws-apigateway-documentation"
  - serverless-plugin-git-variables
  - serverless-python-requirements

resources:
  Description: >
    ${self:service} ${git:branch}:${git:sha1}

    ${git:message}

package:
  patterns:
    - '!**/*'
    - exporter/**

functions:
  generate-signed-url-public: ${file(serverless/functions/generate_signed_url_public.yaml)}
  generate_signed_url: ${file(serverless/functions/generate_signed_url.yaml)}

custom:
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: false
  prune:
    automatic: true
    number: 3
  documentation:
    title: Data Exporter
    version: ${file(metadata.yaml):version}
    summary: Data export API
    description: Creates a signed url that can be used to download the corresponding s3 object.
    models:
      - ${file(./serverless/models/exportRequest.yaml)}
      - ${file(./serverless/models/exportResponse.yaml)}
      - ${file(./serverless/models/awsError.yaml)}
  exportGitVariables: false
