frameworkVersion: ">=1.50.0 <2.0.0"
service: data-exporter

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  iamManagedPolicies:
    - Fn::Join:
      - ':'
      - - 'arn:aws:iam:'
        - Ref: AWS::AccountId
        - 'policy/data-exporter-policy'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    BUCKET: "ok-origo-dataplatform-${self:provider.stage}"
    METADATA_API: ${ssm:/dataplatform/metadata-api/url}
    AUTHORIZER_API: ${ssm:/dataplatform/simple-dataset-authorizer/url}
    ENABLE_AUTH: true
    KEYCLOAK_SERVER: ${ssm:/keycloak/client/server}
    KEYCLOAK_REALM: api-catalog
    CLIENT_ID: data-uploader
    CLIENT_SECRET: ${ssm:/dataplatform/apis/data-uploader/auth/client_secret~true}


plugins:
  - serverless-aws-documentation
  - serverless-pseudo-parameters
  - serverless-plugin-git-variables

resources:
  Description: >
    ${self:service} ${git:branch}:${git:sha1}

    ${git:message}

package:
  exclude:
    - "./**"
  include:
    - exporter/**

functions:
  generate_signed_url: ${file(serverless/functions/generate_signed_url.yaml)}

custom:
  documentation:
    title: Data Exporter
    version: ${file(metadata.yaml):version}
    summary: Data export API
    description: Creates a signed url that can be used to download the corresponding s3 object.
    models:
      - ${file(./serverless/models/exportRequest.yaml)}
      - ${file(./serverless/models/exportResponse.yaml)}
      - ${file(./serverless/models/awsError.yaml)}
  exportGitVariables: false
