name: Deploy Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python 3.11
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: pip install tox
      - name: Test with tox
        run: tox -e py,flake8,black
      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133 # v2
        with:
          use-installer: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_PROD }}:role/github-deploy
          aws-region: eu-west-1
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity
      - name: Build
        run: sam build
      - name: Deploy
        run: |
          GIT_REV="${GITHUB_REF_NAME}:${GITHUB_SHA}"
          sam deploy \
            --config-env prod \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides "Stage=prod GitRev=${GIT_REV}" \
            --tags "GIT_REV=${GIT_REV}"
