name: Deploy Dev
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: pip install tox
    - name: Test with tox
      run: tox -e py,flake8,black
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install NPM dependencies
      run: npm install
    - name: Deploy Lambda functions
      run: |
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_DEV }} \
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }} \
        ./node_modules/.bin/sls deploy -s dev
